
@baseURL=http://localhost
@basePORT=5000

# GET {{baseURL}}:{{basePORT}}/
# Content-Type: "text/plain"

# GET {{baseURL}}:{{basePORT}}/put
# Content-Type: "text/plain"

GET {{baseURL}}:{{basePORT}}/consume
Content-Type: "text/plain"